# Generated by Django 5.0.3 on 2024-06-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': [('upload_templates', 'Is allowed to upload report templates'), ('download_templates', 'Is allowed to download report templates')], 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
    ]
