# Generated by Django 5.0.3 on 2024-11-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['key'], 'permissions': [('upload_templates', 'Is allowed to upload report templates'), ('download_templates', 'Is allowed to download report templates'), ('db_read_access', 'Is allowed connect to db and read data')], 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
    ]
