# Generated by Django 5.0.3 on 2024-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='connection',
            field=models.JSONField(blank=True, help_text='Base information for connection like middleware', null=True, verbose_name='Connection'),
        ),
    ]
