# Generated by Django 5.0.3 on 2024-11-26 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areascope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active')),
                ('desc', models.CharField(blank=True, max_length=80, null=True, verbose_name='desc')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='ctime')),
                ('cuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser')),
                ('utime', models.DateTimeField(blank=True, null=True, verbose_name='utime')),
                ('uuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser')),
                ('key', models.CharField(default='tbd', max_length=80, unique=True, verbose_name='key')),
                ('hex', models.CharField(blank=True, help_text='Hex value for AW data', max_length=8, null=True, verbose_name='hex')),
                ('type', models.CharField(choices=[('S', 'Standard'), ('O', 'Org scope'), ('A', 'App scope'), ('T', 'Test scope')], default='S', help_text='Defines how scope can be used', max_length=1, verbose_name='type')),
                ('bu1_value', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu1_value')),
                ('bu2_value', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu2_value')),
                ('bu3_value', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu3_value')),
                ('bu4_value', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu4_value')),
                ('bu5_value', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu5_value')),
                ('bu1_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu1_title')),
                ('bu2_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu2_title')),
                ('bu3_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu3_title')),
                ('bu4_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu4_title')),
                ('bu5_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='bu5_title')),
                ('team', models.CharField(blank=True, max_length=80, null=True, verbose_name='team')),
                ('app_scope', models.ForeignKey(blank=True, help_text='Here are the standard templates created by Abraxas or other provider', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.areascope')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.area')),
                ('org_scope', models.ForeignKey(blank=True, help_text='Here are the standard templates created by the client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.areascope')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner')),
            ],
            options={
                'verbose_name': 'Mewscope',
                'verbose_name_plural': 'Mewscopes',
            },
        ),
    ]
