# Generated by Django 5.0.3 on 2024-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='propagation_type',
            field=models.CharField(choices=[('no', 'None'), ('sy', 'Synchron'), ('as', 'Asynchron'), ('kafka', 'Kafka')], default='no', max_length=10, verbose_name='propagation_type'),
        ),
    ]
