# Generated by Django 5.0.3 on 2024-11-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areascopes',
            field=models.ManyToManyField(blank=True, to='organization.areascope'),
        ),
        migrations.AddField(
            model_name='user',
            name='use_areascope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.areascope'),
        ),
    ]
