# Generated by Django 5.0.3 on 2024-11-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_user_areascopes_user_use_areascope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='use_scope',
        ),
    ]
