# Generated by Django 5.0.3 on 2024-11-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_container_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='execute_scripts',
            field=models.BooleanField(default=False, help_text='Only if activated scripts will be executed', verbose_name='execute_scripts'),
        ),
    ]
