# Generated by Django 5.0.3 on 2024-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_containertype_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='schematables',
            field=models.CharField(blank=True, help_text='Overwrite default (app.key_area.key)', max_length=40, null=True, verbose_name='schematables'),
        ),
        migrations.AddField(
            model_name='area',
            name='schemaviews',
            field=models.CharField(blank=True, help_text='Overwrite default (app.key_area.key)', max_length=40, null=True, verbose_name='schemaviews'),
        ),
    ]
