# Generated by Django 5.0.3 on 2024-06-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_database_options_application_database_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AddField(
            model_name='database',
            name='database_type',
            field=models.CharField(choices=[('PG', 'PostgreSQL'), ('MD', 'MariaDB'), ('MS', 'MySQL'), ('OR', 'Oracle')], default='PG', max_length=5, verbose_name='pri'),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.client'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='client',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='database',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
