# Generated by Django 5.0.3 on 2024-06-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_container_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Owner',
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='client',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='client',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='If specified, the user may only maintain owner-related objects', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
    ]
