# Generated by Django 5.0.3 on 2024-06-19 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_area_options_database_database_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=80, null=True, verbose_name='desc')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='key')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='ctime')),
                ('cuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser')),
                ('utime', models.DateTimeField(blank=True, null=True, verbose_name='utime')),
                ('uuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser')),
                ('business_unit_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_1')),
                ('business_unit_2', models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_2')),
                ('business_unit_3', models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_3')),
                ('business_unit_4', models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_4')),
                ('business_unit_5', models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_5')),
                ('team', models.CharField(blank=True, max_length=80, null=True, verbose_name='team')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.application')),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
            },
        ),
    ]
