# Generated by Django 5.0.3 on 2024-11-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_container_execute_scripts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerType',
            new_name='ContainerSystem',
        ),
    ]
