# Generated by Django 5.0.3 on 2024-06-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_user_options_scope_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='organization',
        ),
        migrations.AddField(
            model_name='area',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AddField(
            model_name='scope',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='type',
            field=models.CharField(choices=[('S', 'Standard'), ('O', 'Org scope'), ('A', 'App scope')], default='S', help_text='Defines how scope can be used', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
    ]
