# Generated by Django 5.0.3 on 2024-11-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_containertype_containersystem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containersystem',
            options={'verbose_name': 'ContainerSystem', 'verbose_name_plural': 'ContainerSystems'},
        ),
        migrations.RenameField(
            model_name='container',
            old_name='containertype',
            new_name='containersystem',
        ),
    ]
