# Generated by Django 5.0.3 on 2024-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_application_business_unit_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bu1_field',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='fieldname_1'),
        ),
        migrations.AddField(
            model_name='application',
            name='bu2_field',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='fieldname_2'),
        ),
        migrations.AddField(
            model_name='application',
            name='bu3_field',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='fieldname_3'),
        ),
        migrations.AddField(
            model_name='application',
            name='bu4_field',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='fieldname_4'),
        ),
        migrations.AddField(
            model_name='application',
            name='bu5_field',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='fieldname_5'),
        ),
    ]
