# Generated by Django 5.0.3 on 2024-06-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_owner_organization_area_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_of',
            field=models.ManyToManyField(blank=True, related_name='+', to='organization.owner'),
        ),
    ]
