# Generated by Django 5.0.3 on 2024-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_application_bu1_field_application_bu2_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scopes',
        ),
    ]
