# Generated by Django 5.0.3 on 2024-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_client_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='key',
            field=models.CharField(max_length=20, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='database',
            name='database_type',
            field=models.CharField(choices=[('PG', 'PostgreSQL'), ('MD', 'MariaDB'), ('MS', 'MySQL'), ('OR', 'Oracle')], default='PG', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='key',
            field=models.CharField(max_length=80, unique=True, verbose_name='key'),
        ),
    ]
