# Generated by Django 5.0.3 on 2024-06-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_area_key_alter_database_database_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='app_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
        migrations.AddField(
            model_name='scope',
            name='org_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
    ]
