# Generated by Django 5.0.3 on 2024-06-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_group_owner_user_member_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member_of',
            new_name='admin_of',
        ),
    ]
