# Generated by Django 5.0.3 on 2024-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_user_scopes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
