# Generated by Django 5.0.3 on 2024-06-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_member_of_user_admin_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Anwendung', 'verbose_name_plural': 'Anwendungen'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': [('upload_templates', 'Is allowed to upload report templates'), ('download_templates', 'Is allowed to download report templates')], 'verbose_name': 'Container', 'verbose_name_plural': 'Container'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'Containertyp', 'verbose_name_plural': 'Containertypen'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owner'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_of',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('it', 'Italien'), ('fr', 'French'), ('en', 'English')], default='en', help_text='Language used for DATA-Hub UI', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_4',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 4'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_5',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 5'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='application',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='application',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='application',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='area',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='area',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='area',
            name='database',
            field=models.ForeignKey(help_text='Für strukturierte Daten', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.container'),
        ),
        migrations.AlterField(
            model_name='area',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='area',
            name='filestorage',
            field=models.ForeignKey(help_text='Für Dateien', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.container'),
        ),
        migrations.AlterField(
            model_name='area',
            name='key',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='area',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='area',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='container',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='container',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='container',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='container',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='container',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='container',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='container',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='area_add',
            field=models.TextField(blank=True, help_text='Scipt used to add an area to container', null=True, verbose_name='Area hinzufügen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='scope_add',
            field=models.TextField(blank=True, help_text='Script used to add a scope to container', null=True, verbose_name='Scope hinzufügen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='scope_del',
            field=models.TextField(blank=True, help_text='Script used to delete a scope from container', null=True, verbose_name='Scope löschen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='type',
            field=models.CharField(choices=[('DB', 'Datenbank'), ('FS', 'FileStorage')], max_length=2, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_add',
            field=models.TextField(blank=True, help_text='Script used to add a user to container', null=True, verbose_name='User hinzufügen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_del',
            field=models.TextField(blank=True, help_text='Script used to delete a user from container', null=True, verbose_name='User löschen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_from_scope',
            field=models.TextField(blank=True, help_text='Script used to unlink a user from a container', null=True, verbose_name='User vom Scope entfernen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_to_scope',
            field=models.TextField(blank=True, help_text='Script used to link a user to a container', null=True, verbose_name='User für Scope zulassen'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='app_scope',
            field=models.ForeignKey(blank=True, help_text='Hier werden Standard-Templates abgelegt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 1'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 2'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 3'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_4',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 4'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_5',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Geschäftseinheit 5'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit der Erstellung'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User der Erstellung'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='key',
            field=models.CharField(default='tbd', max_length=80, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='team',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='type',
            field=models.CharField(choices=[('S', 'Standard'), ('O', 'Org. Scope'), ('A', 'Anwend. Scope')], default='S', help_text='Legt fest, wie der Scope verwendet werden kann', max_length=1, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeit letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='User letzte Änderung'),
        ),
    ]
