# Generated by Django 5.0.3 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_scope_app_scope_scope_org_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='area_function',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='area_function'),
        ),
        migrations.AddField(
            model_name='database',
            name='user_function',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='user_function'),
        ),
    ]
