# Generated by Django 5.0.3 on 2024-06-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_database_area_function_database_user_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scopes',
            field=models.ManyToManyField(blank=True, null=True, to='organization.scope'),
        ),
        migrations.AlterField(
            model_name='application',
            name='database',
            field=models.ForeignKey(blank=True, help_text='Database can be setted on area level', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.database'),
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='To support hirarchical structures like IGS and SVAs', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.client'),
        ),
        migrations.AlterField(
            model_name='database',
            name='area_function',
            field=models.CharField(blank=True, help_text='Function used to add an area to database', max_length=80, null=True, verbose_name='area_function'),
        ),
        migrations.AlterField(
            model_name='database',
            name='connection',
            field=models.CharField(blank=True, help_text='How to establish connection to database', max_length=200, null=True, verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='database',
            name='user_function',
            field=models.CharField(blank=True, help_text='Function used to add a user to database', max_length=80, null=True, verbose_name='user_function'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='app_scope',
            field=models.ForeignKey(blank=True, help_text='Here are the standard templates created by Abraxas or other provider', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='org_scope',
            field=models.ForeignKey(blank=True, help_text='Here are the standard templates created by the client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
    ]
