# Generated by Django 5.0.3 on 2024-06-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_application_options_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'permissions': [('upload_templates', 'Is allowed to upload report templates'), ('download_templates', 'Is allowed to download report templates')], 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'ContainerType', 'verbose_name_plural': 'ContainerTypes'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='application',
            name='regex_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_4',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_4'),
        ),
        migrations.AlterField(
            model_name='application',
            name='business_unit_5',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_5'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='application',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='application',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='application',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
        migrations.AlterField(
            model_name='area',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='area',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='area',
            name='database',
            field=models.ForeignKey(help_text='To store structured data', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.container'),
        ),
        migrations.AlterField(
            model_name='area',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='area',
            name='filestorage',
            field=models.ForeignKey(help_text='To store files', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.container'),
        ),
        migrations.AlterField(
            model_name='area',
            name='key',
            field=models.CharField(max_length=20, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='area',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='area',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
        migrations.AlterField(
            model_name='container',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='container',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='container',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='container',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='container',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='container',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='container',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='area_add',
            field=models.TextField(blank=True, help_text='Script used to add an area to container', null=True, verbose_name='area_add'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='scope_add',
            field=models.TextField(blank=True, help_text='Script used to add a scope to container', null=True, verbose_name='scope_add'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='scope_del',
            field=models.TextField(blank=True, help_text='Script used to delete a scope from container', null=True, verbose_name='scope_del'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='type',
            field=models.CharField(choices=[('DB', 'DataBase'), ('FS', 'FileStorage')], max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_add',
            field=models.TextField(blank=True, help_text='Script used to add a user to container', null=True, verbose_name='user_add'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_del',
            field=models.TextField(blank=True, help_text='Script used to delete a user from container', null=True, verbose_name='user_del'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_from_scope',
            field=models.TextField(blank=True, help_text='Script used to unlink a user from a container', null=True, verbose_name='user_from_scope'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='user_to_scope',
            field=models.TextField(blank=True, help_text='Script used to link a user to a container', null=True, verbose_name='user_to_scope'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='app_scope',
            field=models.ForeignKey(blank=True, help_text='Here are the standard templates created by Abraxas or other provider', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_1'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_2'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_3'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_4',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_4'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='business_unit_5',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='business_unit_5'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ctime'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='cuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='key',
            field=models.CharField(default='tbd', max_length=80, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='team',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='type',
            field=models.CharField(choices=[('S', 'Standard'), ('O', 'Org scope'), ('A', 'App scope')], default='S', help_text='Defines how scope can be used', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utime'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='uuser',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser'),
        ),
    ]
