# Generated by Django 5.0.3 on 2024-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_application_options_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='regex_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex_2'),
        ),
        migrations.AddField(
            model_name='application',
            name='regex_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex_3'),
        ),
        migrations.AddField(
            model_name='application',
            name='regex_4',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex_4'),
        ),
        migrations.AddField(
            model_name='application',
            name='regex_5',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex_5'),
        ),
        migrations.AlterField(
            model_name='application',
            name='regex_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='regex_1'),
        ),
    ]
