# Generated by Django 5.0.3 on 2024-07-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_application_regex_2_application_regex_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-key'], 'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
    ]
