# Generated by Django 5.0.3 on 2024-06-20 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_database_scope_function_alter_area_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=80, null=True, verbose_name='desc')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='ctime')),
                ('cuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser')),
                ('utime', models.DateTimeField(blank=True, null=True, verbose_name='utime')),
                ('uuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='key')),
                ('area_add', models.TextField(blank=True, help_text='Scipt used to add an area to database', max_length=80, null=True, verbose_name='area_add')),
                ('user_add', models.TextField(blank=True, help_text='Script used to add a user to database', max_length=80, null=True, verbose_name='user_add')),
                ('user_del', models.TextField(blank=True, help_text='Script used to delete a user from database', max_length=80, null=True, verbose_name='user_del')),
                ('scope_add', models.TextField(blank=True, help_text='Script used to add a scope to database', max_length=80, null=True, verbose_name='scope_add')),
                ('scope_del', models.TextField(blank=True, help_text='Script used to delete a scope from database', max_length=80, null=True, verbose_name='scope_del')),
                ('user_to_scope', models.TextField(blank=True, help_text='Script used to link a user to a scope', max_length=80, null=True, verbose_name='user_to_scope')),
                ('user_from_scope', models.TextField(blank=True, help_text='Script used to unlink a user from a scope', max_length=80, null=True, verbose_name='user_from_scope')),
            ],
            options={
                'verbose_name': 'DatabaseType',
                'verbose_name_plural': 'DatabaseTypes',
            },
        ),
    ]
