# Generated by Django 5.0.3 on 2024-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_databasetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='area_function',
        ),
        migrations.RemoveField(
            model_name='database',
            name='scope_function',
        ),
        migrations.RemoveField(
            model_name='database',
            name='user_function',
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='area_add',
            field=models.TextField(blank=True, help_text='Scipt used to add an area to database', null=True, verbose_name='area_add'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='scope_add',
            field=models.TextField(blank=True, help_text='Script used to add a scope to database', null=True, verbose_name='scope_add'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='scope_del',
            field=models.TextField(blank=True, help_text='Script used to delete a scope from database', null=True, verbose_name='scope_del'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='user_add',
            field=models.TextField(blank=True, help_text='Script used to add a user to database', null=True, verbose_name='user_add'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='user_del',
            field=models.TextField(blank=True, help_text='Script used to delete a user from database', null=True, verbose_name='user_del'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='user_from_scope',
            field=models.TextField(blank=True, help_text='Script used to unlink a user from a scope', null=True, verbose_name='user_from_scope'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='user_to_scope',
            field=models.TextField(blank=True, help_text='Script used to link a user to a scope', null=True, verbose_name='user_to_scope'),
        ),
    ]
