# Generated by Django 5.0.3 on 2024-07-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='area',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='container',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='owner',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='scope',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active'),
        ),
    ]
