# Generated by Django 5.0.3 on 2024-06-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_remove_database_area_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='databasetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.databasetype'),
        ),
    ]
