# Generated by Django 5.0.3 on 2024-06-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_database_databasetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='database_type',
        ),
    ]
