# Generated by Django 5.0.3 on 2024-07-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_application_active_area_active_container_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.scope'),
        ),
    ]
