# Generated by Django 5.0.3 on 2024-06-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_database_database_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='databasetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.databasetype'),
        ),
    ]
