# Generated by Django 5.0.3 on 2024-07-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_user_use_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-key'], 'permissions': [('view_dashboard', 'Dasboard for all activities')], 'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
    ]
