# Generated by Django 5.0.3 on 2024-07-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_owner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-key'], 'permissions': [('view_dashboard', 'Can view Dashboard')], 'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
    ]
