# Generated by Django 5.0.3 on 2024-07-15 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_owner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='area',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.application'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner'),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Inactive object is not available for end users', verbose_name='active')),
                ('desc', models.CharField(blank=True, max_length=80, null=True, verbose_name='desc')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='ctime')),
                ('cuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='cuser')),
                ('utime', models.DateTimeField(blank=True, null=True, verbose_name='utime')),
                ('uuser', models.CharField(blank=True, max_length=8, null=True, verbose_name='uuser')),
                ('key', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='key')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='title')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='hostname')),
                ('username', models.CharField(blank=True, max_length=8, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='password')),
                ('ace_connect', models.CharField(blank=True, max_length=256, null=True, verbose_name='ace_connect')),
                ('natproc', models.CharField(blank=True, help_text='Used in batch job.', max_length=8, null=True, verbose_name='natproc')),
                ('awlib', models.CharField(blank=True, help_text='Used in batch job.', max_length=8, null=True, verbose_name='awlib')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.owner')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
            },
        ),
    ]
