# Generated by Django 5.0.3 on 2024-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_application_owner_alter_area_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='title',
            field=models.CharField(max_length=10, verbose_name='title'),
        ),
    ]
