"""
Django settings for datahub project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.conf.locale.en import formats as en_formats
from datetime import datetime




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*jewy(+r67@$v7u7q)s#she6hxiwmri-#*qp3%_l)1hab#rvn8'
PASSWORD = '.Paraolimpia1235'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'organization',
    'maintenance'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datahub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datahub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    
    # 'data_template' is used as template in Container.__connect
    'data_template': {
       'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'sta_usc',
        # 'HOST': 'sta.db.dat.abraxas-apis.ch',
       'PORT': '5432',
       'USER': 'postgres',
       'PASSWORD': PASSWORD,
    },

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'datahub-control.sqlite3',
    }    
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    #{
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    #{
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    #{
    #    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    #},
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
"""
 https://www.thecoderscamp.com/how-to-explicitly-set-django-language-in-django-sessiondjango/
 https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#how-django-discovers-translations
 https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#localization-how-to-create-language-files
 GNU Package: https://mlocati.github.io/articles/gettext-iconv-windows.html

 Kommandos zum Übersetzen (dazu muss das Verzeichnis locale unter abx/aw liegen)
 django-admin makemessages -l de
 django-admin makemessages -a
 django-admin compilemessages
 'django.middleware.locale.LocaleMiddleware', must be used
"""

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

LANGUAGES = [
    ("de", _("German")),
    ("it", _("Italien")),
    ("fr", _("French")),
    ("en", _("English")),
]

LANGUAGE_CODE = 'en'
# LANGUAGE_COOKIE_NAME = 'user_language'

TIME_ZONE = 'MET'

USE_I18N = False

USE_TZ = True

en_formats.DATETIME_FORMAT = "d.m.Y H:i:s"
en_formats.DATE_FORMAT = "d.m.Y"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Log settings added to suppress consol messages of http requests
# https://docs.djangoproject.com/en/5.0/topics/logging/


# Problmes are logged to log_filename
# Changes in databases are logged in data_filename

# log_filename = datetime.now().strftime("log/logstart-%Y-%m-%d-%H-%M.log")
log_filename = datetime.now().strftime("log/log-%Y-%m-%d.log")
data_filename = datetime.now().strftime("log/dbc-%Y-%m-%d.log")
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{'
        },
        
        'verbose': {
#            'format': '{levelname:10} {asctime} {module} {process:d}'
#                '{thread:d} {message}',
            'format': '{levelname:8} {asctime} {message}',
            'datefmt' : "%H:%M:%S",
            'style': '{'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'file': {
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': log_filename
        },
        'datafile': {
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': data_filename
        },
        'console': {
            # 'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'data': {
            'handlers': ['datafile'],
            'level': 'INFO',
            'propagate': False
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    }
}

# Datahub is defining an own AUTH_USER-MODEL
# https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = "organization.User"

# Cookie name keys of owner which the user is allowed to maintain
HUB_ALLOWED_OWNER_KEYS = 'hub_allowed_owner_keys'

HUB_OWNER_KEY = 'ABX'

HUB_APPLICATION_KEY = 'HUB'
